"""add_remarks_columns

Revision ID: 2001e5b1038a
Revises: 3beb61e4edcf
Create Date: 2025-05-31 17:40:19.748456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2001e5b1038a'
down_revision = '3beb61e4edcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_update_vaccines')
    op.drop_table('batch_update_health_materials')
    op.drop_table('batch_update_medicines')
    with op.batch_alter_table('batch_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remarks_priority', sa.String(length=20), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('remarks_priority')
        batch_op.drop_column('remarks')

    op.create_table('batch_update_medicines',
    sa.Column('batch_update_id', sa.INTEGER(), nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['batch_update_id'], ['batch_update.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('batch_update_id', 'medicine_id')
    )
    op.create_table('batch_update_health_materials',
    sa.Column('batch_update_id', sa.INTEGER(), nullable=False),
    sa.Column('health_material_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['batch_update_id'], ['batch_update.id'], ),
    sa.ForeignKeyConstraint(['health_material_id'], ['health_material.id'], ),
    sa.PrimaryKeyConstraint('batch_update_id', 'health_material_id')
    )
    op.create_table('batch_update_vaccines',
    sa.Column('batch_update_id', sa.INTEGER(), nullable=False),
    sa.Column('vaccine_id', sa.INTEGER(), nullable=False),
    sa.Column('dose_number', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['batch_update_id'], ['batch_update.id'], ),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccine.id'], ),
    sa.PrimaryKeyConstraint('batch_update_id', 'vaccine_id')
    )
    # ### end Alembic commands ###
