"""Add phone number fields to Employee model

Revision ID: 37d2ce5de3e3
Revises: 
Create Date: 2025-05-29 18:09:38.073755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d2ce5de3e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('alternate_phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_employee_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_phone_number', type_='unique')
        batch_op.drop_column('alternate_phone_number')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
