"""Add extra_chicks column to batch table

Revision ID: 4ec3b040e355
Revises: add_quantity_per_unit_at_time
Create Date: 2025-06-01 21:39:10.123679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec3b040e355'
down_revision = 'add_quantity_per_unit_at_time'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_batch')
    op.drop_table('batch_update_medicines')
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_chicks', sa.Integer(), nullable=False))
        batch_op.drop_column('extra_chick')

    with op.batch_alter_table('batch_update_feeds', schema=None) as batch_op:
        batch_op.alter_column('quantity_per_unit_at_time',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('price_at_time',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('batch_update_item', schema=None) as batch_op:
        batch_op.alter_column('quantity_per_unit_at_time',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_update_item', schema=None) as batch_op:
        batch_op.alter_column('unit_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('quantity_per_unit_at_time',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('batch_update_feeds', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('price_at_time',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('quantity_per_unit_at_time',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_chick', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('extra_chicks')

    op.create_table('batch_update_medicines',
    sa.Column('batch_update_id', sa.INTEGER(), nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('quantity_per_unit_at_time', sa.FLOAT(), nullable=False),
    sa.Column('unit_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('price_at_time', sa.FLOAT(), nullable=False),
    sa.Column('total_cost', sa.FLOAT(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['batch_update_id'], ['batch_update.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('batch_update_id', 'medicine_id')
    )
    op.create_table('_alembic_tmp_batch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('farm_id', sa.INTEGER(), nullable=False),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=True),
    sa.Column('total_birds', sa.INTEGER(), nullable=False),
    sa.Column('available_birds', sa.INTEGER(), nullable=False),
    sa.Column('total_mortality', sa.INTEGER(), nullable=False),
    sa.Column('feed_stock', sa.FLOAT(), nullable=False),
    sa.Column('shed_birds', sa.TEXT(), nullable=False),
    sa.Column('cost_per_chicken', sa.FLOAT(), nullable=False),
    sa.Column('feed_usage', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('farm_batch_number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
