"""add male female weights and feed return

Revision ID: 5f9b4c2b1a3e
Revises: 2001e5b1038a
Create Date: 2024-07-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9b4c2b1a3e'
down_revision = '2001e5b1038a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_feed_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_update_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_update_id'], ['batch_update.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('male_weight', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('female_weight', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_update', schema=None) as batch_op:
        batch_op.drop_column('female_weight')
        batch_op.drop_column('male_weight')

    op.drop_table('batch_feed_return')
    # ### end Alembic commands ### 