"""add price columns to batch_update_feeds

Revision ID: d74177269ee2
Revises: add_price_columns
Create Date: 2025-06-01 14:38:39.682179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74177269ee2'
down_revision = 'add_price_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.alter_column('farm_batch_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('batch_update_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_at_time', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_update_feeds', schema=None) as batch_op:
        batch_op.drop_column('total_cost')
        batch_op.drop_column('price_at_time')

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.alter_column('farm_batch_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
