"""add_farm_batch_number

Revision ID: ede81553d412
Revises: 2001e5b1038a
Create Date: 2025-05-31 18:35:06.832245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'ede81553d412'
down_revision = '2001e5b1038a'
branch_labels = None
depends_on = None


def upgrade():
    # # 1. Add as nullable
    # op.add_column('batch', sa.Column('farm_batch_number', sa.Integer(), nullable=True))

    # 2. Populate for existing rows (assign sequential numbers per farm)
    connection = op.get_bind()
    farms = connection.execute(text('SELECT id FROM farm')).fetchall()
    for farm in farms:
        farm_id = farm[0]
        batches = connection.execute(
            text('SELECT id FROM batch WHERE farm_id = :farm_id ORDER BY created_at'),
            {'farm_id': farm_id}
        ).fetchall()
        for index, batch in enumerate(batches, 1):
            connection.execute(
                text('UPDATE batch SET farm_batch_number = :num WHERE id = :batch_id'),
                {'num': index, 'batch_id': batch[0]}
            )

    # 3. Make non-nullable
    # op.alter_column('batch', 'farm_batch_number', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('farm_batch_number')

    # ### end Alembic commands ###
